### ISSUE TITLE
Support for 1366x768

### ISSUE THREAD

**Issue by lucretiaa** [X3ne/hsrpc#8]
Currently there is no support for 1366x768 full screen but I believe this could easily be implemented. There are some instances where it reads the screen correctly (viewing travel log, changing settings, "Inovocate" for warp/wishing) but at other points it'll just say "In combat" incorrectly most of the time or "lost in the space-time continuum." It'd be nice if support was added for this resolution!

**Comment by X3ne** [comment]
Hi, thanks for testing this resolution and hsrpc! I released an update that calculates menu positions without having to enter the coordinates manually but unfortunately it broke a lot of menus. I'm working on version 1.3 to fix a lot of problems but I'm currently on vacation and I'll try to release an update as soon as possible (I've started working on it #7).

**Comment by X3ne** [comment]
Hi, I've released the [version 1.3](https://github.com/X3ne/hsrpc/releases/tag/v1.3.0). I tested with my 1080p screen set to a resolution of 1366x768 and a game resolution of 1366x768 and obtained good results (in fullscreen). Feel free to reopen an issue, this help me to improve this app (if the application crashes or fails to start up, please refer to [the warning](https://github.com/X3ne/hsrpc?tab=readme-ov-file#-technical-information)). Please note that some menus are not currently supported, so please refer to the [development progress](https://github.com/X3ne/hsrpc?tab=readme-ov-file#-known-issues)
